[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
